em: Solve taking ⌃U as asking to pass a Signed Int to the Called Chords
add Eggs ⌃U-0 and ⌃U009⌃Z from the Eggs of Emacs 'C-u universal-argument'

for now do leave ⌃U args not doing much, just ringing the Terminal Bell, such as
    NotImplementedError: ⌃U -1 ⌃U 0 Repeat Count  ?
    NotImplementedError: ⌃U 9 ⌃Z Repeat Count  ?

hunk-by-hunk details =>

-- def do_vi_prefix_chord --

rewrite for clarity and commonality with 'def do_em_prefix_chord'

-- def check_vi_count --

shuffle all the work out into 'editor.check_repeat_count'

-- def do_vi_sig_tstp --

do think to raise NotImplementedError: Repeat Count
    when called with a Repeat Count

-- def format_vi_status --

shuffle the work of formatting the TerminalNudgeIn Self into its Class

-- def eval_vi_prefix --

first commit, factor out of 'def choose_chords_func'

-- def do_em_prefix_chord --

first commit,
to take ⌃U { ⌃U } [ "-" ] { "0123456789" } [ ⌃U ] as a Prefix to more Chords

-- def eval_em_prefix --

first commit,
for the classic Emacs move of take a string of "⌃U" as a power of 4,
and take the "⌃U -" to mean "⌃U - 1"

-- TerminalNudgeIn def to_chars --
-- TerminalNudgeIn def _to_echoed_chars --

first commit of these two Def's,
to do the work of formatting the TerminalNudgeIn Self,
but also echo the whole Prefix, no longer just its meaning,
and also keep Prefix separate from Chords, to speak such Emacs thoughts as
    3,2  NotImplementedError: ⌃U 123 ⌃U 9 Repeat Count  ?

Basic Vim runs without needing this work, but basic Emacs needs it

-- def check_repeat_count --

factor out of 'def check_vi_count' and 'def raise_blame_for_chords_func'

for Em Py, raise not-implemented ⌃U - as ⌃U -1, and ⌃U ⌃U as ⌃U 16, and so on
    don't lose the not-implemented ⌃U args like Emacs ⌃J, ⌃S, ⌃R, ⌃Z, etc

-- raise_blame_for_chords_func --

shuffle the work of 'def check_repeat_count' out into that new Def

-- def do_raise_name_error --

raise an Exception for the Chords not found,
stop the miscue of raising it for the Prefix + Chords

shuffle the work of formatting the TerminalNudgeIn Self into its Class

-- def repr_vi_nudge_bytes --

disappear up into the TerminalNudgeIn Class